version: '3'
services:
  ds-datag:
    image: developmentseed/ds-datag:v1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
        - ./:/mnt
    working_dir: /mnt
    ports:
      - '8888:8888'
